services:
  material-backend:
    image: material-back:1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: material_back
    env_file:
      - .env
    ports:
      - "${FASTAPI_PORT:-9876}:9876"
    restart: unless-stopped
